// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type EventRegistrationsStatus string

const (
	EventRegistrationsStatusInterested EventRegistrationsStatus = "interested"
	EventRegistrationsStatusRegistered EventRegistrationsStatus = "registered"
)

func (e *EventRegistrationsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventRegistrationsStatus(s)
	case string:
		*e = EventRegistrationsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EventRegistrationsStatus: %T", src)
	}
	return nil
}

type NullEventRegistrationsStatus struct {
	EventRegistrationsStatus EventRegistrationsStatus `json:"event_registrations_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if EventRegistrationsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventRegistrationsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EventRegistrationsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventRegistrationsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventRegistrationsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventRegistrationsStatus), nil
}

type EventsEventType string

const (
	EventsEventTypeOffline EventsEventType = "offline"
	EventsEventTypeOnline  EventsEventType = "online"
)

func (e *EventsEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventsEventType(s)
	case string:
		*e = EventsEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for EventsEventType: %T", src)
	}
	return nil
}

type NullEventsEventType struct {
	EventsEventType EventsEventType `json:"events_event_type"`
	Valid           bool            `json:"valid"` // Valid is true if EventsEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventsEventType) Scan(value interface{}) error {
	if value == nil {
		ns.EventsEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventsEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventsEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventsEventType), nil
}

type JobsJobType string

const (
	JobsJobTypeFullTime JobsJobType = "full_time"
	JobsJobTypePartTime JobsJobType = "part_time"
	JobsJobTypeRemote   JobsJobType = "remote"
	JobsJobTypeContract JobsJobType = "contract"
)

func (e *JobsJobType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobsJobType(s)
	case string:
		*e = JobsJobType(s)
	default:
		return fmt.Errorf("unsupported scan type for JobsJobType: %T", src)
	}
	return nil
}

type NullJobsJobType struct {
	JobsJobType JobsJobType `json:"jobs_job_type"`
	Valid       bool        `json:"valid"` // Valid is true if JobsJobType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobsJobType) Scan(value interface{}) error {
	if value == nil {
		ns.JobsJobType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobsJobType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobsJobType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobsJobType), nil
}

type UsersRole string

const (
	UsersRoleAlumni UsersRole = "alumni"
	UsersRoleAdmin  UsersRole = "admin"
)

func (e *UsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRole(s)
	case string:
		*e = UsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRole: %T", src)
	}
	return nil
}

type NullUsersRole struct {
	UsersRole UsersRole `json:"users_role"`
	Valid     bool      `json:"valid"` // Valid is true if UsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRole), nil
}

type UsersStatus string

const (
	UsersStatusUnverified UsersStatus = "unverified"
	UsersStatusActive     UsersStatus = "active"
	UsersStatusSuspended  UsersStatus = "suspended"
)

func (e *UsersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersStatus(s)
	case string:
		*e = UsersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersStatus: %T", src)
	}
	return nil
}

type NullUsersStatus struct {
	UsersStatus UsersStatus `json:"users_status"`
	Valid       bool        `json:"valid"` // Valid is true if UsersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UsersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersStatus), nil
}

type EmailVerification struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	Used      bool      `json:"used"`
	CreatedAt time.Time `json:"created_at"`
}

type Event struct {
	ID          string          `json:"id"`
	Title       string          `json:"title"`
	Description sql.NullString  `json:"description"`
	Location    sql.NullString  `json:"location"`
	EventType   EventsEventType `json:"event_type"`
	ZoomLink    sql.NullString  `json:"zoom_link"`
	StartTime   time.Time       `json:"start_time"`
	EndTime     sql.NullTime    `json:"end_time"`
	Thumbnail   sql.NullString  `json:"thumbnail"`
	AuthorID    sql.NullString  `json:"author_id"`
	Published   bool            `json:"published"`
	CreatedAt   time.Time       `json:"created_at"`
}

type EventRegistration struct {
	ID        string                   `json:"id"`
	EventID   string                   `json:"event_id"`
	UserID    string                   `json:"user_id"`
	Status    EventRegistrationsStatus `json:"status"`
	CreatedAt time.Time                `json:"created_at"`
}

type Job struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	Company     string         `json:"company"`
	Location    sql.NullString `json:"location"`
	JobType     JobsJobType    `json:"job_type"`
	Description sql.NullString `json:"description"`
	ApplyUrl    sql.NullString `json:"apply_url"`
	PostedBy    sql.NullString `json:"posted_by"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
	Published   bool           `json:"published"`
	CreatedAt   time.Time      `json:"created_at"`
}

type News struct {
	ID        string         `json:"id"`
	Title     string         `json:"title"`
	Slug      string         `json:"slug"`
	Content   string         `json:"content"`
	Thumbnail sql.NullString `json:"thumbnail"`
	Category  sql.NullString `json:"category"`
	AuthorID  sql.NullString `json:"author_id"`
	Published bool           `json:"published"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type PasswordReset struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	Used      bool      `json:"used"`
	CreatedAt time.Time `json:"created_at"`
}

type Profile struct {
	UserID         string         `json:"user_id"`
	PhotoUrl       sql.NullString `json:"photo_url"`
	Phone          sql.NullString `json:"phone"`
	GraduationYear sql.NullInt16  `json:"graduation_year"`
	Major          sql.NullString `json:"major"`
	City           sql.NullString `json:"city"`
	JobTitle       sql.NullString `json:"job_title"`
	Company        sql.NullString `json:"company"`
	Bio            sql.NullString `json:"bio"`
	LinkedinUrl    sql.NullString `json:"linkedin_url"`
	UpdatedAt      time.Time      `json:"updated_at"`
	InstagramUrl   sql.NullString `json:"instagram_url"`
}

type RefreshToken struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Survey struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	FormUrl     string         `json:"form_url"`
	AuthorID    sql.NullString `json:"author_id"`
	Active      bool           `json:"active"`
	CreatedAt   time.Time      `json:"created_at"`
}

type User struct {
	ID        string      `json:"id"`
	FullName  string      `json:"full_name"`
	BirthYear int16       `json:"birth_year"`
	Email     string      `json:"email"`
	Password  string      `json:"password"`
	Status    UsersStatus `json:"status"`
	Role      UsersRole   `json:"role"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}
