// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countAlumni = `-- name: CountAlumni :one
SELECT COUNT(*) FROM users WHERE status = 'active' AND role = 'alumni'
`

func (q *Queries) CountAlumni(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAlumni)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailVerification = `-- name: CreateEmailVerification :exec
INSERT INTO email_verifications (id, user_id, token, expires_at)
VALUES (UUID(), ?, ?, ?)
`

type CreateEmailVerificationParams struct {
	UserID    string    `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error {
	_, err := q.db.ExecContext(ctx, createEmailVerification, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}

const createEvent = `-- name: CreateEvent :execresult
INSERT INTO events (id, title, description, location, event_type, zoom_link, start_time, end_time, thumbnail, author_id, published)
VALUES (UUID(), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEventParams struct {
	Title       string          `json:"title"`
	Description sql.NullString  `json:"description"`
	Location    sql.NullString  `json:"location"`
	EventType   EventsEventType `json:"event_type"`
	ZoomLink    sql.NullString  `json:"zoom_link"`
	StartTime   time.Time       `json:"start_time"`
	EndTime     sql.NullTime    `json:"end_time"`
	Thumbnail   sql.NullString  `json:"thumbnail"`
	AuthorID    sql.NullString  `json:"author_id"`
	Published   bool            `json:"published"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEvent,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.EventType,
		arg.ZoomLink,
		arg.StartTime,
		arg.EndTime,
		arg.Thumbnail,
		arg.AuthorID,
		arg.Published,
	)
}

const createEventRegistration = `-- name: CreateEventRegistration :exec
INSERT INTO event_registrations (id, event_id, user_id, status)
VALUES (UUID(), ?, ?, ?)
ON DUPLICATE KEY UPDATE status = VALUES(status)
`

type CreateEventRegistrationParams struct {
	EventID string                   `json:"event_id"`
	UserID  string                   `json:"user_id"`
	Status  EventRegistrationsStatus `json:"status"`
}

func (q *Queries) CreateEventRegistration(ctx context.Context, arg CreateEventRegistrationParams) error {
	_, err := q.db.ExecContext(ctx, createEventRegistration, arg.EventID, arg.UserID, arg.Status)
	return err
}

const createJob = `-- name: CreateJob :execresult
INSERT INTO jobs (id, title, company, location, job_type, description, apply_url, posted_by, expires_at, published)
VALUES (UUID(), ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateJobParams struct {
	Title       string         `json:"title"`
	Company     string         `json:"company"`
	Location    sql.NullString `json:"location"`
	JobType     JobsJobType    `json:"job_type"`
	Description sql.NullString `json:"description"`
	ApplyUrl    sql.NullString `json:"apply_url"`
	PostedBy    sql.NullString `json:"posted_by"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
	Published   bool           `json:"published"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createJob,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.JobType,
		arg.Description,
		arg.ApplyUrl,
		arg.PostedBy,
		arg.ExpiresAt,
		arg.Published,
	)
}

const createNews = `-- name: CreateNews :execresult
INSERT INTO news (id, title, slug, content, thumbnail, category, author_id, published)
VALUES (UUID(), ?, ?, ?, ?, ?, ?, ?)
`

type CreateNewsParams struct {
	Title     string         `json:"title"`
	Slug      string         `json:"slug"`
	Content   string         `json:"content"`
	Thumbnail sql.NullString `json:"thumbnail"`
	Category  sql.NullString `json:"category"`
	AuthorID  sql.NullString `json:"author_id"`
	Published bool           `json:"published"`
}

func (q *Queries) CreateNews(ctx context.Context, arg CreateNewsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createNews,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Thumbnail,
		arg.Category,
		arg.AuthorID,
		arg.Published,
	)
}

const createPasswordReset = `-- name: CreatePasswordReset :exec
INSERT INTO password_resets (id, user_id, token, expires_at)
VALUES (UUID(), ?, ?, ?)
`

type CreatePasswordResetParams struct {
	UserID    string    `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordReset, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, token_hash, expires_at)
VALUES (UUID(), ?, ?, ?)
`

type CreateRefreshTokenParams struct {
	UserID    string    `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createSurvey = `-- name: CreateSurvey :execresult
INSERT INTO surveys (id, title, description, form_url, author_id, active)
VALUES (UUID(), ?, ?, ?, ?, ?)
`

type CreateSurveyParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	FormUrl     string         `json:"form_url"`
	AuthorID    sql.NullString `json:"author_id"`
	Active      bool           `json:"active"`
}

func (q *Queries) CreateSurvey(ctx context.Context, arg CreateSurveyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSurvey,
		arg.Title,
		arg.Description,
		arg.FormUrl,
		arg.AuthorID,
		arg.Active,
	)
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (id, full_name, birth_year, email, password, status, role)
VALUES (UUID(), ?, ?, ?, ?, 'unverified', 'alumni')
`

type CreateUserParams struct {
	FullName  string `json:"full_name"`
	BirthYear int16  `json:"birth_year"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.FullName,
		arg.BirthYear,
		arg.Email,
		arg.Password,
	)
}

const deleteAllUserRefreshTokens = `-- name: DeleteAllUserRefreshTokens :exec
DELETE FROM refresh_tokens WHERE user_id = ?
`

func (q *Queries) DeleteAllUserRefreshTokens(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllUserRefreshTokens, userID)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = ?
`

func (q *Queries) DeleteEvent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs WHERE id = ?
`

func (q *Queries) DeleteJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const deleteNews = `-- name: DeleteNews :exec
DELETE FROM news
WHERE id = ?
`

func (q *Queries) DeleteNews(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNews, id)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens WHERE token_hash = ?
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, tokenHash)
	return err
}

const deleteSurvey = `-- name: DeleteSurvey :exec
DELETE FROM surveys
WHERE id = ?
`

func (q *Queries) DeleteSurvey(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSurvey, id)
	return err
}

const getEmailVerification = `-- name: GetEmailVerification :one
SELECT id, user_id, token, expires_at, used
FROM email_verifications
WHERE token = ? AND used = 0 AND expires_at > NOW()
LIMIT 1
`

type GetEmailVerificationRow struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	Used      bool      `json:"used"`
}

func (q *Queries) GetEmailVerification(ctx context.Context, token string) (GetEmailVerificationRow, error) {
	row := q.db.QueryRowContext(ctx, getEmailVerification, token)
	var i GetEmailVerificationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, title, description, location, event_type, zoom_link, start_time, end_time, thumbnail, created_at
FROM events
WHERE id = ? AND published = 1
LIMIT 1
`

type GetEventByIDRow struct {
	ID          string          `json:"id"`
	Title       string          `json:"title"`
	Description sql.NullString  `json:"description"`
	Location    sql.NullString  `json:"location"`
	EventType   EventsEventType `json:"event_type"`
	ZoomLink    sql.NullString  `json:"zoom_link"`
	StartTime   time.Time       `json:"start_time"`
	EndTime     sql.NullTime    `json:"end_time"`
	Thumbnail   sql.NullString  `json:"thumbnail"`
	CreatedAt   time.Time       `json:"created_at"`
}

func (q *Queries) GetEventByID(ctx context.Context, id string) (GetEventByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.EventType,
		&i.ZoomLink,
		&i.StartTime,
		&i.EndTime,
		&i.Thumbnail,
		&i.CreatedAt,
	)
	return i, err
}

const getEventByIDPrivate = `-- name: GetEventByIDPrivate :one
SELECT id, title, description, location, event_type, zoom_link, start_time, end_time, thumbnail, author_id, published, created_at
FROM events
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetEventByIDPrivate(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByIDPrivate, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.EventType,
		&i.ZoomLink,
		&i.StartTime,
		&i.EndTime,
		&i.Thumbnail,
		&i.AuthorID,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, title, company, location, job_type, description, apply_url, posted_by, expires_at, published, created_at
FROM jobs
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetJobByID(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.JobType,
		&i.Description,
		&i.ApplyUrl,
		&i.PostedBy,
		&i.ExpiresAt,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const getNewsByIDPrivate = `-- name: GetNewsByIDPrivate :one
SELECT id, title, slug, content, thumbnail, category, author_id, published, created_at
FROM news
WHERE id = ?
LIMIT 1
`

type GetNewsByIDPrivateRow struct {
	ID        string         `json:"id"`
	Title     string         `json:"title"`
	Slug      string         `json:"slug"`
	Content   string         `json:"content"`
	Thumbnail sql.NullString `json:"thumbnail"`
	Category  sql.NullString `json:"category"`
	AuthorID  sql.NullString `json:"author_id"`
	Published bool           `json:"published"`
	CreatedAt time.Time      `json:"created_at"`
}

func (q *Queries) GetNewsByIDPrivate(ctx context.Context, id string) (GetNewsByIDPrivateRow, error) {
	row := q.db.QueryRowContext(ctx, getNewsByIDPrivate, id)
	var i GetNewsByIDPrivateRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Thumbnail,
		&i.Category,
		&i.AuthorID,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const getNewsBySlug = `-- name: GetNewsBySlug :one
SELECT n.id, n.title, n.slug, n.content, n.thumbnail, n.category, n.published, n.created_at,
       u.full_name AS author_name
FROM news n
LEFT JOIN users u ON u.id = n.author_id
WHERE n.slug = ? AND n.published = 1
LIMIT 1
`

type GetNewsBySlugRow struct {
	ID         string         `json:"id"`
	Title      string         `json:"title"`
	Slug       string         `json:"slug"`
	Content    string         `json:"content"`
	Thumbnail  sql.NullString `json:"thumbnail"`
	Category   sql.NullString `json:"category"`
	Published  bool           `json:"published"`
	CreatedAt  time.Time      `json:"created_at"`
	AuthorName sql.NullString `json:"author_name"`
}

func (q *Queries) GetNewsBySlug(ctx context.Context, slug string) (GetNewsBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getNewsBySlug, slug)
	var i GetNewsBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Thumbnail,
		&i.Category,
		&i.Published,
		&i.CreatedAt,
		&i.AuthorName,
	)
	return i, err
}

const getOrCreateProfile = `-- name: GetOrCreateProfile :one
SELECT user_id, photo_url, phone, graduation_year, major, city, job_title, company, bio, linkedin_url, instagram_url, updated_at
FROM profiles
WHERE user_id = ?
LIMIT 1
`

type GetOrCreateProfileRow struct {
	UserID         string         `json:"user_id"`
	PhotoUrl       sql.NullString `json:"photo_url"`
	Phone          sql.NullString `json:"phone"`
	GraduationYear sql.NullInt16  `json:"graduation_year"`
	Major          sql.NullString `json:"major"`
	City           sql.NullString `json:"city"`
	JobTitle       sql.NullString `json:"job_title"`
	Company        sql.NullString `json:"company"`
	Bio            sql.NullString `json:"bio"`
	LinkedinUrl    sql.NullString `json:"linkedin_url"`
	InstagramUrl   sql.NullString `json:"instagram_url"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) GetOrCreateProfile(ctx context.Context, userID string) (GetOrCreateProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateProfile, userID)
	var i GetOrCreateProfileRow
	err := row.Scan(
		&i.UserID,
		&i.PhotoUrl,
		&i.Phone,
		&i.GraduationYear,
		&i.Major,
		&i.City,
		&i.JobTitle,
		&i.Company,
		&i.Bio,
		&i.LinkedinUrl,
		&i.InstagramUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasswordReset = `-- name: GetPasswordReset :one
SELECT id, user_id, token, expires_at, used
FROM password_resets
WHERE token = ? AND used = 0 AND expires_at > NOW()
LIMIT 1
`

type GetPasswordResetRow struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	Used      bool      `json:"used"`
}

func (q *Queries) GetPasswordReset(ctx context.Context, token string) (GetPasswordResetRow, error) {
	row := q.db.QueryRowContext(ctx, getPasswordReset, token)
	var i GetPasswordResetRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at
FROM refresh_tokens
WHERE token_hash = ? AND expires_at > NOW()
LIMIT 1
`

type GetRefreshTokenRow struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, tokenHash)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
	)
	return i, err
}

const getSurveyByID = `-- name: GetSurveyByID :one
SELECT id, title, description, form_url, author_id, active, created_at
FROM surveys
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSurveyByID(ctx context.Context, id string) (Survey, error) {
	row := q.db.QueryRowContext(ctx, getSurveyByID, id)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.FormUrl,
		&i.AuthorID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, birth_year, email, password, status, role, created_at, updated_at
FROM users
WHERE email = ?
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.BirthYear,
		&i.Email,
		&i.Password,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, birth_year, email, password, status, role, created_at, updated_at
FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.BirthYear,
		&i.Email,
		&i.Password,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserEventRegistration = `-- name: GetUserEventRegistration :one
SELECT id, event_id, user_id, status, created_at
FROM event_registrations
WHERE event_id = ? AND user_id = ?
LIMIT 1
`

type GetUserEventRegistrationParams struct {
	EventID string `json:"event_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) GetUserEventRegistration(ctx context.Context, arg GetUserEventRegistrationParams) (EventRegistration, error) {
	row := q.db.QueryRowContext(ctx, getUserEventRegistration, arg.EventID, arg.UserID)
	var i EventRegistration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listAlumni = `-- name: ListAlumni :many
SELECT u.id, u.full_name, u.birth_year, u.email, u.status, u.role, u.created_at,
       p.photo_url, p.city, p.job_title, p.company, p.graduation_year, p.major, p.linkedin_url, p.instagram_url
FROM users u
LEFT JOIN profiles p ON p.user_id = u.id
WHERE u.status = 'active'
  AND u.role = 'alumni'
  AND (? = '' OR u.full_name LIKE CONCAT('%', ?, '%') OR p.city LIKE CONCAT('%', ?, '%'))
ORDER BY u.full_name ASC
LIMIT ? OFFSET ?
`

type ListAlumniParams struct {
	Column1  interface{} `json:"column_1"`
	CONCAT   interface{} `json:"CONCAT"`
	CONCAT_2 interface{} `json:"CONCAT_2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListAlumniRow struct {
	ID             string         `json:"id"`
	FullName       string         `json:"full_name"`
	BirthYear      int16          `json:"birth_year"`
	Email          string         `json:"email"`
	Status         UsersStatus    `json:"status"`
	Role           UsersRole      `json:"role"`
	CreatedAt      time.Time      `json:"created_at"`
	PhotoUrl       sql.NullString `json:"photo_url"`
	City           sql.NullString `json:"city"`
	JobTitle       sql.NullString `json:"job_title"`
	Company        sql.NullString `json:"company"`
	GraduationYear sql.NullInt16  `json:"graduation_year"`
	Major          sql.NullString `json:"major"`
	LinkedinUrl    sql.NullString `json:"linkedin_url"`
	InstagramUrl   sql.NullString `json:"instagram_url"`
}

func (q *Queries) ListAlumni(ctx context.Context, arg ListAlumniParams) ([]ListAlumniRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlumni,
		arg.Column1,
		arg.CONCAT,
		arg.CONCAT_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlumniRow{}
	for rows.Next() {
		var i ListAlumniRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.BirthYear,
			&i.Email,
			&i.Status,
			&i.Role,
			&i.CreatedAt,
			&i.PhotoUrl,
			&i.City,
			&i.JobTitle,
			&i.Company,
			&i.GraduationYear,
			&i.Major,
			&i.LinkedinUrl,
			&i.InstagramUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, title, description, location, event_type, zoom_link, start_time, end_time, thumbnail, created_at
FROM events
WHERE published = 1
ORDER BY start_time ASC
LIMIT ? OFFSET ?
`

type ListEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListEventsRow struct {
	ID          string          `json:"id"`
	Title       string          `json:"title"`
	Description sql.NullString  `json:"description"`
	Location    sql.NullString  `json:"location"`
	EventType   EventsEventType `json:"event_type"`
	ZoomLink    sql.NullString  `json:"zoom_link"`
	StartTime   time.Time       `json:"start_time"`
	EndTime     sql.NullTime    `json:"end_time"`
	Thumbnail   sql.NullString  `json:"thumbnail"`
	CreatedAt   time.Time       `json:"created_at"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.EventType,
			&i.ZoomLink,
			&i.StartTime,
			&i.EndTime,
			&i.Thumbnail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsPrivate = `-- name: ListEventsPrivate :many
SELECT id, title, description, location, event_type, zoom_link, start_time, end_time, thumbnail, author_id, published, created_at
FROM events
WHERE author_id = ? OR ? = 1
ORDER BY start_time DESC
LIMIT ? OFFSET ?
`

type ListEventsPrivateParams struct {
	AuthorID sql.NullString `json:"author_id"`
	Column2  interface{}    `json:"column_2"`
	Limit    int32          `json:"limit"`
	Offset   int32          `json:"offset"`
}

func (q *Queries) ListEventsPrivate(ctx context.Context, arg ListEventsPrivateParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsPrivate,
		arg.AuthorID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.EventType,
			&i.ZoomLink,
			&i.StartTime,
			&i.EndTime,
			&i.Thumbnail,
			&i.AuthorID,
			&i.Published,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, title, company, location, job_type, apply_url, expires_at, created_at
FROM jobs
WHERE published = 1 AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListJobsRow struct {
	ID        string         `json:"id"`
	Title     string         `json:"title"`
	Company   string         `json:"company"`
	Location  sql.NullString `json:"location"`
	JobType   JobsJobType    `json:"job_type"`
	ApplyUrl  sql.NullString `json:"apply_url"`
	ExpiresAt sql.NullTime   `json:"expires_at"`
	CreatedAt time.Time      `json:"created_at"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]ListJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsRow{}
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.JobType,
			&i.ApplyUrl,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNews = `-- name: ListNews :many
SELECT id, title, slug, thumbnail, category, published, created_at
FROM news
WHERE published = 1
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListNewsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListNewsRow struct {
	ID        string         `json:"id"`
	Title     string         `json:"title"`
	Slug      string         `json:"slug"`
	Thumbnail sql.NullString `json:"thumbnail"`
	Category  sql.NullString `json:"category"`
	Published bool           `json:"published"`
	CreatedAt time.Time      `json:"created_at"`
}

func (q *Queries) ListNews(ctx context.Context, arg ListNewsParams) ([]ListNewsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNews, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNewsRow{}
	for rows.Next() {
		var i ListNewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Thumbnail,
			&i.Category,
			&i.Published,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsPrivate = `-- name: ListNewsPrivate :many
SELECT id, title, slug, content, thumbnail, category, author_id, published, created_at
FROM news
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListNewsPrivateParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListNewsPrivateRow struct {
	ID        string         `json:"id"`
	Title     string         `json:"title"`
	Slug      string         `json:"slug"`
	Content   string         `json:"content"`
	Thumbnail sql.NullString `json:"thumbnail"`
	Category  sql.NullString `json:"category"`
	AuthorID  sql.NullString `json:"author_id"`
	Published bool           `json:"published"`
	CreatedAt time.Time      `json:"created_at"`
}

func (q *Queries) ListNewsPrivate(ctx context.Context, arg ListNewsPrivateParams) ([]ListNewsPrivateRow, error) {
	rows, err := q.db.QueryContext(ctx, listNewsPrivate, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNewsPrivateRow{}
	for rows.Next() {
		var i ListNewsPrivateRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Thumbnail,
			&i.Category,
			&i.AuthorID,
			&i.Published,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSurveys = `-- name: ListSurveys :many
SELECT id, title, description, form_url, created_at
FROM surveys
WHERE active = 1
ORDER BY created_at DESC
`

type ListSurveysRow struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	FormUrl     string         `json:"form_url"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) ListSurveys(ctx context.Context) ([]ListSurveysRow, error) {
	rows, err := q.db.QueryContext(ctx, listSurveys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSurveysRow{}
	for rows.Next() {
		var i ListSurveysRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.FormUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSurveysPrivate = `-- name: ListSurveysPrivate :many
SELECT id, title, description, form_url, author_id, active, created_at
FROM surveys
ORDER BY created_at DESC
`

func (q *Queries) ListSurveysPrivate(ctx context.Context) ([]Survey, error) {
	rows, err := q.db.QueryContext(ctx, listSurveysPrivate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Survey{}
	for rows.Next() {
		var i Survey
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.FormUrl,
			&i.AuthorID,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerificationUsed = `-- name: MarkEmailVerificationUsed :exec
UPDATE email_verifications SET used = 1 WHERE token = ?
`

func (q *Queries) MarkEmailVerificationUsed(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, markEmailVerificationUsed, token)
	return err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_resets SET used = 1 WHERE token = ?
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetUsed, token)
	return err
}

const updateEvent = `-- name: UpdateEvent :exec
UPDATE events
SET title = ?, description = ?, location = ?, event_type = ?, zoom_link = ?, start_time = ?, end_time = ?, thumbnail = ?, published = ?
WHERE id = ?
`

type UpdateEventParams struct {
	Title       string          `json:"title"`
	Description sql.NullString  `json:"description"`
	Location    sql.NullString  `json:"location"`
	EventType   EventsEventType `json:"event_type"`
	ZoomLink    sql.NullString  `json:"zoom_link"`
	StartTime   time.Time       `json:"start_time"`
	EndTime     sql.NullTime    `json:"end_time"`
	Thumbnail   sql.NullString  `json:"thumbnail"`
	Published   bool            `json:"published"`
	ID          string          `json:"id"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.ExecContext(ctx, updateEvent,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.EventType,
		arg.ZoomLink,
		arg.StartTime,
		arg.EndTime,
		arg.Thumbnail,
		arg.Published,
		arg.ID,
	)
	return err
}

const updateJob = `-- name: UpdateJob :exec
UPDATE jobs
SET title = ?, company = ?, location = ?, job_type = ?, description = ?, apply_url = ?, expires_at = ?, published = ?
WHERE id = ?
`

type UpdateJobParams struct {
	Title       string         `json:"title"`
	Company     string         `json:"company"`
	Location    sql.NullString `json:"location"`
	JobType     JobsJobType    `json:"job_type"`
	Description sql.NullString `json:"description"`
	ApplyUrl    sql.NullString `json:"apply_url"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
	Published   bool           `json:"published"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) error {
	_, err := q.db.ExecContext(ctx, updateJob,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.JobType,
		arg.Description,
		arg.ApplyUrl,
		arg.ExpiresAt,
		arg.Published,
		arg.ID,
	)
	return err
}

const updateNews = `-- name: UpdateNews :exec
UPDATE news
SET title = ?, content = ?, thumbnail = ?, category = ?, published = ?
WHERE id = ?
`

type UpdateNewsParams struct {
	Title     string         `json:"title"`
	Content   string         `json:"content"`
	Thumbnail sql.NullString `json:"thumbnail"`
	Category  sql.NullString `json:"category"`
	Published bool           `json:"published"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateNews(ctx context.Context, arg UpdateNewsParams) error {
	_, err := q.db.ExecContext(ctx, updateNews,
		arg.Title,
		arg.Content,
		arg.Thumbnail,
		arg.Category,
		arg.Published,
		arg.ID,
	)
	return err
}

const updateSurvey = `-- name: UpdateSurvey :exec
UPDATE surveys
SET title = ?, description = ?, form_url = ?, active = ?
WHERE id = ?
`

type UpdateSurveyParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	FormUrl     string         `json:"form_url"`
	Active      bool           `json:"active"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateSurvey(ctx context.Context, arg UpdateSurveyParams) error {
	_, err := q.db.ExecContext(ctx, updateSurvey,
		arg.Title,
		arg.Description,
		arg.FormUrl,
		arg.Active,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password = ? WHERE id = ?
`

type UpdateUserPasswordParams struct {
	Password string `json:"password"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Password, arg.ID)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET status = ? WHERE id = ?
`

type UpdateUserStatusParams struct {
	Status UsersStatus `json:"status"`
	ID     string      `json:"id"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.Status, arg.ID)
	return err
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO profiles (user_id, photo_url, phone, graduation_year, major, city, job_title, company, bio, linkedin_url, instagram_url)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    photo_url       = VALUES(photo_url),
    phone           = VALUES(phone),
    graduation_year = VALUES(graduation_year),
    major           = VALUES(major),
    city            = VALUES(city),
    job_title       = VALUES(job_title),
    company         = VALUES(company),
    bio             = VALUES(bio),
    linkedin_url    = VALUES(linkedin_url),
    instagram_url   = VALUES(instagram_url),
    updated_at      = CURRENT_TIMESTAMP
`

type UpsertProfileParams struct {
	UserID         string         `json:"user_id"`
	PhotoUrl       sql.NullString `json:"photo_url"`
	Phone          sql.NullString `json:"phone"`
	GraduationYear sql.NullInt16  `json:"graduation_year"`
	Major          sql.NullString `json:"major"`
	City           sql.NullString `json:"city"`
	JobTitle       sql.NullString `json:"job_title"`
	Company        sql.NullString `json:"company"`
	Bio            sql.NullString `json:"bio"`
	LinkedinUrl    sql.NullString `json:"linkedin_url"`
	InstagramUrl   sql.NullString `json:"instagram_url"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertProfile,
		arg.UserID,
		arg.PhotoUrl,
		arg.Phone,
		arg.GraduationYear,
		arg.Major,
		arg.City,
		arg.JobTitle,
		arg.Company,
		arg.Bio,
		arg.LinkedinUrl,
		arg.InstagramUrl,
	)
	return err
}
